TEST:
  ENABLE: False
  DATASET: Ssv2_patch
  BATCH_SIZE: 2
TRAIN:
  ENABLE: False
  DATASET: Ssv2_patch
  BATCH_SIZE: 2
  GLOBAL_BATCH_SIZE: 256
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: ""
DATA:
  PATH_TO_JPEG: ""
  PATH_TO_ANNOTATION: ""
  TRAIN_SPLIT_DIR: ""
  VAL_SPLIT_DIR: ""
  TEST_SPLIT_DIR: ""
  NUM_FRAMES: 32
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_RANDOM_FLIP: False
  TRAIN_COLORJITTER: False
  TRAIN_RAND_AUGMENT: True
  CROP_SIZE: 224
  INV_UNIFORM_SAMPLE: True
SOLVER:
  BASE_LR: 1.0e-4
  REFERENCE_BATCH_SIZE: 256
  LR_POLICY: cosine
  COSINE_END_LR: 1.0e-06
  MAX_EPOCH: 15
  WEIGHT_DECAY: 5.0e-2
  SMOOTHING: 0.2
  OPTIMIZING_METHOD: mt_adamw
  USE_MIXED_PRECISION: True
KCENTER_MOTIONFORMER:
  NUM_HYBRID_FRAMES: 0
MODEL:
  NUM_CLASSES: 174
  MODEL_NAME: kcenter_motionformer
  LOSS_FUNC: cross_entropy
  METRIC_FUNC: topk_errors
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 1
LOG_PERIOD: 10
RNG_SEED: 0
OUTPUT_DIR: ""
EVALUATE_INIT: False